spring.application.name=thesisplatform

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/thesisPlatform
spring.datasource.username=postgres
spring.datasource.password=Pepino123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=debug
logging.level.org.flywaydb=info
logging.level.org.springframework.security=info

# ===============================
# ERRORS
# ===============================
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false

# ===============================
# SECURITY
# ===============================
jwt.secret=bXktc3VwZXItc2VjcmV0LWtleS1mb3ItdGhlc2lzcGxhdGZvcm0tMjAyNg==
jwt.expiration=86400000

# ===============================
# PASSWORD RESET
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tfgplataforma04@gmail.com
spring.mail.password=rgug mizo gkdc gdyz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties[mail.smtp.connectiontimeout]=5000
spring.mail.properties[mail.smtp.timeout]=3000
spring.mail.properties[mail.smtp.writetimeout]=5000
app.mail.from=plataforma.tfg.directores@gmail.com
app.frontend.reset-password-url=http://localhost:3000/reset-password